import type { Artist, Artwork } from "./types.ts";
import { MET_ARTWORKS } from "./metArtworks.ts";

const artists = {
  nocturne: {
    id: "10000000-0000-0000-0000-000000000001",
    slug: "atelier-nocturne-demo",
    name: "Atelier Nocturne — Demo",
    nationality: "Synthetic development identity",
    biography: "A fictional studio identity created exclusively for ARTE development, testing, and interface validation. No real artist or representation is implied.",
  },
  lumen: {
    id: "10000000-0000-0000-0000-000000000002",
    slug: "forma-lumen-demo",
    name: "Forma Lumen — Demo",
    nationality: "Synthetic development identity",
    biography: "A fictional studio identity used to test geometric, minimal, and light-driven presentation inside ARTE. All associated works are synthetic demo records.",
  },
  vale: {
    id: "10000000-0000-0000-0000-000000000003",
    slug: "maris-vale-demo",
    name: "Maris Vale — Demo",
    nationality: "Synthetic development identity",
    biography: "A fictional studio identity created to exercise ARTE’s landscape, color, and atmospheric discovery flows without making rights claims about real artwork.",
  },
  anima: {
    id: "10000000-0000-0000-0000-000000000004",
    slug: "studio-anima-demo",
    name: "Studio Anima — Demo",
    nationality: "Synthetic development identity",
    biography: "A fictional studio identity created for figurative and expressive demo material. It exists only inside the ARTE development dataset.",
  },
} satisfies Record<string, Artist>;

const sharedRights = {
  imageSource: "ARTE deterministic demo renderer",
  rightsHolder: "ARTE development dataset",
  license: "Development-only synthetic content",
  usageNotes: "Synthetic demo presentation. No real artwork, sale, ownership, or artist representation is implied.",
  sourceUrl: "/sources/demo",
};

export const SYNTHETIC_ARTWORKS: Artwork[] = [
  {
    id: "30000000-0000-0000-0000-000000000001",
    slug: "quiet-red-study-demo",
    title: "Quiet Red Study — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1200 × 1600 px",
    description: "A restrained field of oxblood, charcoal, and warm mineral light.",
    movement: "Demo Abstraction",
    tags: ["oxblood", "quiet", "geometric"],
    features: { palette: ["oxblood", "charcoal", "warm"], mood: ["quiet", "introspective"], composition: ["compressed", "centered"], subjects: ["abstraction"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.nocturne,
    visual: { kind: "gradient", aspect: "portrait", aspectRatio: "4 / 5", background: "linear-gradient(145deg, #1d1716 0%, #4f2028 47%, #b4835f 100%)", accent: "#e5c49d", shape: "orb", alt: "Synthetic abstract composition with a dark red field and a warm circular form." },
    recommendationReason: "A measured palette and compressed composition introduce ARTE’s demo collection.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000002",
    slug: "night-window-demo",
    title: "Night Window — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1600 × 1200 px",
    description: "A nocturnal architectural study held between violet and amber light.",
    movement: "Demo Figurative",
    tags: ["night", "architecture", "violet"],
    features: { palette: ["violet", "charcoal", "warm"], mood: ["nocturnal", "introspective"], composition: ["framed", "compressed"], subjects: ["architecture", "interior"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.nocturne,
    visual: { kind: "gradient", aspect: "landscape", aspectRatio: "4 / 3", background: "linear-gradient(125deg, #11131d 0%, #302b55 52%, #9a6849 100%)", accent: "#f0c78d", shape: "frame", alt: "Synthetic nocturnal composition with violet space and an amber rectangular opening." },
    recommendationReason: "Its dim architecture extends the tonal restraint of the opening work.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000003",
    slug: "form-three-demo",
    title: "Form III — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1400 × 1400 px",
    description: "A square study in proportion, tension, and antique-gold interruption.",
    movement: "Demo Minimalism",
    tags: ["minimal", "square", "gold"],
    features: { palette: ["ivory", "stone", "gold"], mood: ["quiet", "measured"], composition: ["geometric", "asymmetric"], subjects: ["form"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.lumen,
    visual: { kind: "gradient", aspect: "square", aspectRatio: "1 / 1", background: "linear-gradient(160deg, #ece7dc 0%, #b9ad96 58%, #4d4942 100%)", accent: "#6a1f2b", shape: "bands", alt: "Synthetic square composition with pale mineral tones and a narrow oxblood band." },
    recommendationReason: "A quieter geometric counterpoint adds medium and compositional diversity.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000004",
    slug: "image-awaiting-clearance-demo",
    title: "Image Awaiting Clearance — Demo",
    year: "2026",
    medium: "Metadata-only synthetic record",
    dimensions: "Dimensions unavailable",
    description: "An intentional missing-image state used to verify graceful rights-first presentation.",
    movement: "Demo Systems Study",
    tags: ["missing image", "rights", "fallback"],
    features: { palette: ["ivory", "gray"], mood: ["neutral"], composition: ["framed"], subjects: ["rights system"], mediumCategory: "metadata record", period: "contemporary demo", geography: "synthetic" },
    artist: artists.lumen,
    visual: { kind: "missing", aspect: "portrait", aspectRatio: "4 / 5", background: "#e8e2d7", accent: "#77736b", shape: "frame", alt: "Artwork image intentionally unavailable while rights information is reviewed." },
    recommendationReason: "ARTE includes records without displayable imagery instead of silently breaking the feed.",
    isDemo: true,
    rights: { ...sharedRights, usageNotes: "Intentional missing-image test record. No image is displayed or claimed." },
  },
  {
    id: "30000000-0000-0000-0000-000000000005",
    slug: "blue-interval-demo",
    title: "Blue Interval — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1800 × 1200 px",
    description: "An open blue field interrupted by a soft, off-center horizon.",
    movement: "Demo Color Field",
    tags: ["blue", "horizon", "calm"],
    features: { palette: ["blue", "stone", "ivory"], mood: ["calm", "expansive"], composition: ["horizon", "open"], subjects: ["landscape", "abstraction"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.vale,
    visual: { kind: "gradient", aspect: "landscape", aspectRatio: "3 / 2", background: "linear-gradient(180deg, #24344d 0%, #6f8aa0 58%, #d8c9ae 59%, #b09a7c 100%)", accent: "#f4ead9", shape: "veil", alt: "Synthetic blue landscape-like field with a pale horizontal interval." },
    recommendationReason: "A broader horizon expands the feed beyond enclosed architectural space.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000006",
    slug: "garden-after-rain-demo",
    title: "Garden After Rain — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1350 × 1800 px",
    description: "Layered greens and washed rose tones suggest a garden without literal depiction.",
    movement: "Demo Atmospheric",
    tags: ["green", "garden", "texture"],
    features: { palette: ["green", "rose", "ivory"], mood: ["calm", "tender"], composition: ["layered", "vertical"], subjects: ["garden", "landscape"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.vale,
    visual: { kind: "gradient", aspect: "portrait", aspectRatio: "3 / 4", background: "linear-gradient(150deg, #26372f 0%, #71806a 45%, #c89b91 78%, #efe0c7 100%)", accent: "#551c2b", shape: "orb", alt: "Synthetic atmospheric composition of layered green, rose, and cream tones." },
    recommendationReason: "Shared atmospheric softness connects it to the prior horizon while changing palette and orientation.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000007",
    slug: "electric-figure-demo",
    title: "Electric Figure — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1200 × 1600 px",
    description: "A high-contrast vertical form staged against electric cobalt and ember tones.",
    movement: "Demo Expressionism",
    tags: ["figure", "cobalt", "energy"],
    features: { palette: ["cobalt", "ember", "charcoal"], mood: ["energetic", "dramatic"], composition: ["vertical", "high contrast"], subjects: ["figure"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.anima,
    visual: { kind: "gradient", aspect: "portrait", aspectRatio: "4 / 5", background: "linear-gradient(135deg, #171326 0%, #244dc2 45%, #d46b42 100%)", accent: "#f5e8c8", shape: "veil", alt: "Synthetic expressive vertical composition in cobalt, ember, and cream." },
    recommendationReason: "A deliberate increase in contrast introduces expressive energy without repeating an artist.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000008",
    slug: "dust-and-gold-demo",
    title: "Dust and Gold — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1600 × 1200 px",
    description: "Muted earth tones hold a narrow line of reflective warmth.",
    movement: "Demo Material Study",
    tags: ["earth", "gold", "material"],
    features: { palette: ["earth", "gold", "warm"], mood: ["quiet", "grounded"], composition: ["horizontal", "layered"], subjects: ["material", "abstraction"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.lumen,
    visual: { kind: "gradient", aspect: "landscape", aspectRatio: "4 / 3", background: "linear-gradient(120deg, #322d29 0%, #857461 60%, #c8a76a 61%, #e6d5b5 100%)", accent: "#f3e4c8", shape: "bands", alt: "Synthetic earth-toned composition with a narrow antique-gold interruption." },
    recommendationReason: "Material warmth reconnects the feed to the gold accent used in earlier minimal work.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000009",
    slug: "meridian-demo",
    title: "Meridian — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1500 × 1500 px",
    description: "A centered axis divides cool depth from mineral light.",
    movement: "Demo Minimalism",
    tags: ["axis", "blue", "minimal"],
    features: { palette: ["blue", "ivory", "stone"], mood: ["measured", "calm"], composition: ["centered", "geometric"], subjects: ["form", "abstraction"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.lumen,
    visual: { kind: "gradient", aspect: "square", aspectRatio: "1 / 1", background: "linear-gradient(90deg, #1c2634 0%, #52677c 49%, #c8b690 50%, #eee3cf 100%)", accent: "#6a1f2b", shape: "frame", alt: "Synthetic square composition split between blue depth and pale mineral light." },
    recommendationReason: "A stable central axis creates a formal pause after textured and figurative works.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000010",
    slug: "violet-assembly-demo",
    title: "Violet Assembly — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1200 × 1600 px",
    description: "Overlapping violet structures gather around a muted interior light.",
    movement: "Demo Abstraction",
    tags: ["violet", "layered", "structure"],
    features: { palette: ["violet", "charcoal", "warm"], mood: ["introspective", "quiet"], composition: ["compressed", "layered"], subjects: ["architecture", "abstraction"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.nocturne,
    visual: { kind: "gradient", aspect: "portrait", aspectRatio: "4 / 5", background: "linear-gradient(155deg, #21162e 0%, #5c426d 55%, #c7a58b 100%)", accent: "#f0dfc8", shape: "frame", alt: "Synthetic violet composition with layered rectangular structures and warm interior light." },
    recommendationReason: "It revisits a known demo artist only after substantial movement and medium variation.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000011",
    slug: "tidal-memory-demo",
    title: "Tidal Memory — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1800 × 1200 px",
    description: "A low, tidal sweep moves through deep teal and weathered ivory.",
    movement: "Demo Atmospheric",
    tags: ["teal", "water", "memory"],
    features: { palette: ["teal", "ivory", "stone"], mood: ["calm", "reflective"], composition: ["horizon", "open"], subjects: ["water", "landscape"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.vale,
    visual: { kind: "gradient", aspect: "landscape", aspectRatio: "3 / 2", background: "linear-gradient(170deg, #17343a 0%, #47777a 55%, #d4c8ae 80%, #f4eddf 100%)", accent: "#71303c", shape: "veil", alt: "Synthetic teal and ivory composition suggesting a low tidal sweep." },
    recommendationReason: "Atmospheric continuity returns with a cooler palette and wider visual rhythm.",
    isDemo: true,
    rights: sharedRights,
  },
  {
    id: "30000000-0000-0000-0000-000000000012",
    slug: "small-monument-demo",
    title: "Small Monument — Demo",
    year: "2026",
    medium: "Synthetic digital study",
    dimensions: "1400 × 1400 px",
    description: "A compact dark form stands against a luminous, nearly architectural ground.",
    movement: "Demo Sculptural Study",
    tags: ["monument", "form", "light"],
    features: { palette: ["ivory", "earth", "charcoal"], mood: ["quiet", "solemn"], composition: ["centered", "geometric"], subjects: ["monument", "form"], mediumCategory: "digital study", period: "contemporary demo", geography: "synthetic" },
    artist: artists.anima,
    visual: { kind: "gradient", aspect: "square", aspectRatio: "1 / 1", background: "linear-gradient(140deg, #ebe1cf 0%, #bfae90 60%, #6b5b4a 100%)", accent: "#191919", shape: "orb", alt: "Synthetic square composition with a compact dark form against a luminous ground." },
    recommendationReason: "A sculptural-feeling close gives the initial collection a distinct final silhouette.",
    isDemo: true,
    rights: sharedRights,
  },
];

// Preserve fixture IDs for existing saves and demo flows; discovery uses only real works.
export const DEMO_ARTWORKS: Artwork[] = [...SYNTHETIC_ARTWORKS, ...MET_ARTWORKS];
export const GALLERY_ARTWORKS: Artwork[] = DEMO_ARTWORKS.filter((artwork) => !artwork.isDemo);
export const DEMO_ARTISTS: Artist[] = [...new Map(DEMO_ARTWORKS.map(({ artist }) => [artist.id, artist])).values()];
